version: '3.8'

services:
  
  # 1. Layanan Backend (Express)
  server:
    # Memberi tahu Docker untuk build dari folder './server'
    # (Ini akan otomatis mencari 'server/Dockerfile')
    build: ./server
    container_name: skm_server
    # Muat variabel (MONGO_URI) dari file .env ini
    env_file: ./server/.env
    volumes:
      # Memasang file rahasia Firebase Anda ke dalam container
      - ./firebase-service-account.json:/app/src/config/firebase-service-account.json

  # 2. Layanan Frontend (React)
  client:
    # Memberi tahu Docker untuk build dari folder './client'
    # (Ini akan otomatis mencari 'client/Dockerfile')
    build: ./client
    container_name: skm_client

  # 3. Layanan Nginx (Reverse Proxy)
  nginx:
    # Memberi tahu Docker untuk build dari folder './nginx'
    # (Ini akan otomatis mencari 'nginx/Dockerfile')
    build: ./nginx
    container_name: skm_nginx
    ports:
      # Buka port 80 di PC Anda dan arahkan ke port 80 di container Nginx
      - "80:80" 
    depends_on:
      # Jangan nyalakan Nginx sebelum server dan client siap
      - server
      - client

# Kita tidak lagi membutuhkan 'volumes: mysql_data' karena kita menggunakan MongoDB Atlas